app/admin/forms.py
from flask import current_app
from flask_babel import lazy_gettext as _l, _
from flask_wtf import FlaskForm, RecaptchaField
from werkzeug.security import check_password_hash
from wtforms import StringField, SubmitField, BooleanField, PasswordField, TextAreaField, \
    SelectMultipleField
from wtforms.fields.html5 import EmailField
from wtforms.validators import DataRequired, NumberRange
from wtforms_components import IntegerField, Email

from app.model.Guest import Guest


class GuestForm(FlaskForm):
    name = StringField(_l('Name'), validators=[DataRequired()])
    email = EmailField(_l('E-mail'), validators=[DataRequired(), Email()])
    number_of_guests = IntegerField(_l('Number of guests'), default=0, validators=[NumberRange(0, 20)])
    food_allergies = TextAreaField(_l('Food allergies'))
    favourite_music = TextAreaField(_l('Favourite music'),
                                    description=_l("Do you have some music, you'd really like to listen?"))
    notes = TextAreaField(_l('Other important notes'))
    will_attend = BooleanField(_l('I will attend'))
    submit = SubmitField('Submit')

    def set_model(self, guest: Guest):
        self.name.data = guest.name
        self.email.data = guest.email
        self.notes.data = guest.notes
        self.number_of_guests.data = guest.number_of_guests
        self.food_allergies.data = guest.food_allergies
        self.will_attend.data = guest.will_attend
        self.favourite_music.data = guest.favourite_music

    def fill_model(self, guest: Guest):
        guest.name = self.name.data
        guest.email = self.email.data
        guest.notes = self.notes.data
        guest.number_of_guests = self.number_of_guests.data
        guest.food_allergies = self.food_allergies.data
        guest.will_attend = self.will_attend.data
        guest.favourite_music = self.favourite_music.data
        return guest


class LoginForm(FlaskForm):
    password = PasswordField(_l('Password'), validators=[DataRequired()])
    remember_me = BooleanField(_l('Remember Me'))
    recaptcha = RecaptchaField()
    submit = SubmitField(_l('Sign In'))

    def validate_login(self):
        return check_password_hash(current_app.config["ADMIN_PASSWORD_HASH"], self.password.data)


class EmailForm(FlaskForm):
    subject = StringField(_l('Subject'), validators=[DataRequired()])
    recipients = SelectMultipleField(_l('Send To'), validators=[DataRequired()],
                                     render_kw={'multiple': None, 'data-live-search': "true", 'class': "selectpicker"},
                                     choices=[("all", _("Send to all"))])
    body = TextAreaField(_l('E-mail body'), validators=[DataRequired()])
    submit = SubmitField(_l('Send'))

app/admin/__init__.py
from flask import Blueprint

admin = Blueprint('admin', __name__, template_folder='templates')

from . import views         # noqa: F401, E402

app/admin/views.py
import os

from flask import render_template, redirect, url_for, abort, flash, request, Response
from flask_babel import _
from flask_login import login_required
from flask_login import login_user, logout_user

from app.admin import admin
from app.admin.forms import GuestForm, LoginForm, EmailForm
from app.model.Admin import Admin
from app.model.Guest import Guest
from app.services.EmailSender import EmailSender
from app.services.CSVHandler import CSVHandler


@admin.route('/', methods=['GET'])
@login_required
def admin_dashboard():
    guest_list = [guest for guest in Guest.scan()]

    max_guests = int(os.getenv("MAX_GUEST_COUNT", 200))
    return render_template("admin_dashboard.html", title=_("Admin page"), guest_list=guest_list,
                           max_guests=max_guests)


@admin.route('/guest/add', methods=['GET', 'POST'])
@login_required
def add_guest():
    form = GuestForm()
    if form.validate_on_submit():
        guest = Guest()
        form.fill_model(guest)
        guest.save()
        return redirect(url_for("admin.list_guest"))
    return render_template('guest_form.html', form=form, title=_("Add guest"))


@admin.route('/guest/edit/<string:guest_id>', methods=['GET', 'POST'])
@login_required
def edit_guest(guest_id):
    form = GuestForm()
    guest = Guest.find(guest_id) or abort(404)
    if form.validate_on_submit():
        form.fill_model(guest)
        guest.filled_by_admin = True
        guest.save()
        return redirect(url_for("admin.list_guest"))
    form.set_model(guest)
    return render_template('guest_form.html', form=form, title=_("Edit guest"))


@admin.route('/guest/list', methods=['GET', 'POST'])
@login_required
def list_guest():
    guest_list = Guest.scan()
    return render_template('guest_list.html', guests=guest_list, title=_("Guest list"))


@admin.route('/guest/delete/<string:guest_id>', methods=['POST'])
@login_required
def delete_guest(guest_id):
    guest = Guest.find(guest_id) or abort(404)
    guest.delete()
    flash(_("Guest {} removed".format(guest.name)))
    return redirect(url_for("admin.list_guest"))


@admin.route('/login', methods=['GET', 'POST'])
def login():
    form = LoginForm()
    if form.validate_on_submit():
        logout_user()           # just to be sure we wipe any leftover session cookie
        user = Admin()
        if not form.validate_login():
            flash(_('Invalid username or password'))
            return redirect(url_for('admin.login'))
        login_user(user, remember=form.remember_me.data)
        return redirect(url_for("admin.admin_dashboard"))
    return render_template('login.html', title=_('Sign In'), form=form)


@admin.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('admin.login'))


@admin.route('/email_sender', methods=['GET', 'POST'])
@login_required
def email_sender():
    form = EmailForm()
    form.recipients.choices.extend([(str(g.id), g.name) for g in Guest.scan()])
    if form.validate_on_submit():
        footer = _("Your RSVP link: ") + f"{request.url_root}rsvp/{{id}}" + "\n"
        footer += _("Unsubscribe and delete my data: ") + f"{request.url_root}rsvp/unsubscribe/{{id}}?email={{email}}"
        emailsender = EmailSender(os.getenv("SENDER_SMTP_SERVER"), os.getenv("SENDER_EMAIL_ADDRESS"),
                                  os.getenv("SMTP_USER"), os.getenv("SMTP_PASSWORD"), footer_template=footer)

        if "all" in form.recipients.data:
            guests = Guest.scan()
        else:
            guests = Guest.find_multi_id(form.recipients.data)
        success, failed = emailsender.send_emails(guests, form.subject.data, form.body.data)
        if success:
            flash(str(len(success)) + _(" E-mails sent successfully"), "success")
        if failed:
            flash(str(len(failed)) + _(" E-mails couldn't be sent"), "warning")

    return render_template('email_sender.html', title=_('Send mail'), form=form)


@admin.route('/guest/import', methods=['POST'])
@login_required
def import_guests():
    if CSVHandler.import_csv(request.files["csv_file"].read().decode("utf-8")):
        flash(_("Guest list imported successfully"), "success")
    else:
        flash(_("Guest list import was unsuccessful"), "error")
    return redirect(url_for("admin.list_guest"))


@admin.route('/guest/export', methods=['GET'])
@login_required
def export_guests():
    response = Response(CSVHandler.export_csv().getvalue(), mimetype='text/csv')
    response.headers.set("Content-Disposition", "attachment", filename="guests.csv")
    return response

app/admin/templates/admin_base.html
<!DOCTYPE html>
<html>

<head>
    <title>{{ title }}</title>
    {% block styles %}
    <link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.5.3/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
    {% endblock %}
</head>
<body>

{% block navbar %}
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="{{ url_for('admin.admin_dashboard') }}">{{ _('Admin') }}</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav">
            <li class="nav-item"><a class="nav-link" href="{{ url_for('admin.admin_dashboard') }}">{{ _('Dashboard') }}</a></li>
            <li class="nav-item"><a class="nav-link" href="{{ url_for('admin.list_guest') }}">{{ _('Guest list') }}</a></li>
            <li class="nav-item"><a class="nav-link" href="{{ url_for('admin.email_sender') }}">{{ _('E-mail sender') }}</a></li>
        </ul>
        <ul class="navbar-nav ml-auto">
            {% if current_user.is_anonymous %}
            <li><a class="nav-link" href="{{ url_for('admin.login') }}">{{ _('Login') }}</a></li>
            {% else %}
            <li><a class="nav-link" href="{{ url_for('admin.logout') }}">{{ _('Logout') }}</a></li>
            {% endif %}
        </ul>
    </div>
</nav>
{% endblock %}

<div class="container">
    {% with messages = get_flashed_messages(with_categories=true) %}
    {% if messages %}
    {% for category, message in messages %}
    <div class="alert alert-{{ category }}" role="alert">{{ message }}</div>
    {% endfor %}
    {% endif %}
    {% endwith %}
    {% block app_content %}{% endblock %}
</div>
{% block scripts %}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.5.3/js/bootstrap.bundle.min.js"></script>
{% endblock %}
</body>
</html>

app/admin/templates/admin_dashboard.html
{% extends 'admin_base.html' %}

{% block app_content %}
<div class="container">
    <div class="row">
        <div class="col-md-2"><p>{{_("Guest count")}}</p></div>
        <div class="col-md-10">
            <div class="progress" id="guest_counter">
                {% set guest_count = guest_list | sum(attribute='number_of_guests') %}
                {% set color = "bg-success" if guest_count <= max_guests else "bg-danger"%}
              <div class="progress-bar {{color}} progress-bar-striped progress-bar-animated"
                   style="width:{{ 100 * (guest_list | sum(attribute='number_of_guests'))/max_guests}}%">
                  {{ guest_list | sum(attribute='number_of_guests') }} / {{ max_guests }}</div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-2"><p>{{_("Responses")}}</p></div>
        <div class="col-md-10">
            <div class="progress" id="response_counter">
              {% set all_guests = guest_list | length  %}
                {% if all_guests != 0 %}
                  {% set answered = guest_list | selectattr('last_responded') | list | length  %}
                  {% set filled_by_admin = guest_list | selectattr('filled_by_admin') | rejectattr('last_responded') | list | length%}
                  {% set viewed = guest_list | selectattr('last_viewed') | rejectattr('last_responded') | rejectattr('filled_by_admin') | list | length  %}

                  <div class="progress-bar bg-success progress-bar-striped progress-bar-animated"
                       id="response_answered" style="width:{{100 * answered / all_guests}}%">
                      {{_("Answered")}} ({{(answered)}})
                  </div>
                  <div class="progress-bar bg-info progress-bar-striped progress-bar-animated"
                       id="response_admin_filled" style="width:{{100 * filled_by_admin / all_guests}}%">
                    {{_("Filled by admin")}} ({{filled_by_admin}})
                  </div>
                  <div class="progress-bar bg-warning progress-bar-striped progress-bar-animated"
                       id="response_seen" style="width:{{100 * (viewed) / all_guests}}%">
                    {{_("Seen but not filled")}} ({{(viewed)}})
                  </div>
                  <div class="progress-bar bg-danger progress-bar-striped progress-bar-animated"
                       id="response_remaining" style="width:{{100 * (all_guests-viewed-filled_by_admin-answered) / all_guests}}%">
                    {{_("Remaining")}} ({{(all_guests-viewed-filled_by_admin-answered)}})
                  </div>
                {% else %}
                    {{_("No guests yet...")}}
                {% endif %}
            </div>
        </div>
    </div>
    </div>
    <div class="row">
        <div class="col-md-6">
        <h4>{{_("Recently responded")}}</h4>
        <table class="table table-striped table-bordered" id="recently_responded">
        <thead>
        <tr>
            <th width="25%"> {{_('Name')}}</th>
            <th width="25%"> {{_('When')}}</th>
            <th width="10%"> {{_('Coming')}}</th>
        </tr>
        </thead>
        <tbody>
        {% for guest in (guest_list|rejectattr('last_responded', 'none')|sort(attribute='last_responded', reverse=True))[:10] %}
        <tr>
            <td> {{ guest.name }}</td>
            <td> {{ guest.last_responded.strftime('%Y-%m-%d %H:%M') }}</td>
            <td>
                <i class="fa {% if guest.will_attend == True %} fa-check {% else %} fa-minus-square {% endif %}"></i>
            </td>
        </tr>
        {% endfor %}
        </tbody>
        </table>
        </div>

        <div class="col-md-6">
        <h4>{{_("Still missing")}}</h4>
        <table class="table table-striped table-bordered" id="still_missing">
        <thead>
        <tr>
            <th width="25%"> {{_('Name')}}</th>
            <th width="10%"> {{_('Edit')}}</th>
        </tr>
        </thead>
        <tbody>
        {% for guest in (guest_list|rejectattr('filled_by_admin')|selectattr('last_responded', 'none')) %}
        <tr>
            <td> {{ guest.name }}</td>
            <td>
                <a class="btn btn-link" href="{{ url_for('admin.edit_guest', guest_id=guest.id) }}">
                    <i class="fa fa-pencil"></i>
                </a>
            </td>
        </tr>
        {% endfor %}
        </tbody>
        </table>
        </div>

    </div>


    <div class="row">
        <div class="col-md-6">
        <h4>{{_("Food")}}</h4>
        <table class="table table-striped table-bordered" id="food_allergies">
        <thead>
        <tr>
            <th width="25%"> {{_('Name')}}</th>
            <th width="25%"> {{_('Food allergies')}}</th>
        </tr>
        </thead>
        <tbody>
        {% for guest in guest_list|rejectattr('food_allergies', 'none')|rejectattr('food_allergies', 'equalto','') %}
        <tr>
            <td> {{ guest.name }}</td>
            <td> {{ guest.food_allergies }}</td>
        </tr>
        {% endfor %}
        </tbody>
        </table>
        </div>

        <div class="col-md-6">
        <h4>{{_("Music")}}</h4>
        <table class="table table-striped table-bordered" id="requested_songs">
        <thead>
        <tr>
            <th width="25%"> {{_('Name')}}</th>
            <th width="25%"> {{_('Favourite music')}}</th>
        </tr>
        </thead>
        <tbody>
        {% for guest in (guest_list|rejectattr('favourite_music', 'none')|rejectattr('favourite_music', 'equalto','')) %}
        <tr>
            <td> {{ guest.name }}</td>
            <td> {{ guest.favourite_music }}</td>
        </tr>
        {% endfor %}
        </tbody>
        </table>
        </div>

    </div>

</div>

{% endblock %}

app/admin/templates/email_sender.html
{% extends 'admin_base.html' %}

{% from "macros.html" import generate_form %}

{% block styles %}
{{super()}}
<link href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.13.18/css/bootstrap-select.min.css" rel="stylesheet">
{% endblock %}

{% block app_content %}

{{generate_form(form)}}

{% endblock %}

{% block scripts %}
{{super()}}
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.13.18/js/bootstrap-select.min.js"></script>
{% endblock %}

app/admin/templates/guest_form.html
{% extends 'admin_base.html' %}

{% from "macros.html" import generate_form %}

{% block app_content %}

{{generate_form(form)}}

{% endblock %}

app/admin/templates/guest_list.html
{% extends 'admin_base.html' %}

{% block app_content %}
<div class="content-section">
    <div class="outer">
        <div class="middle">
            <div class="inner">
                <br/>
                <br/>
                <h1 style="text-align:center;">{{_("Guests")}}</h1>
                <hr class="intro-divider">
                <div class="center">
                    <form action="{{ url_for('admin.import_guests') }}" method="post" enctype="multipart/form-data">
                        <div class="input-group">
                            <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>
                            <div class="custom-file">
                                <input type="file" name="csv_file" class="custom-file-input" id="import-csv">
                                <label class="custom-file-label" for="import-csv">{{_("Choose file")}}</label>
                            </div>
                            <div class="input-group-append">
                                <button class="btn btn-outline-default" type="submit">
                                    <i class="fa fa-upload"></i>{{_("Import")}}
                                </button>
                            </div>
                        </div>
                    </form>
                    <a class="btn btn-link" href="{{ url_for('admin.export_guests') }}">
                        <i class="fa fa-download"></i>
                    </a>

                    <table class="table table-striped table-bordered">
                        <thead>
                        <tr>
                            <th width="35%"> {{_('Name')}}</th>
                            <th width="30%"> {{_('E-mail')}}</th>
                            <th width="10%"> {{_('Guest count')}}</th>
                            <th width="5%"> {{_('Viewed')}}</th>
                            <th width="5%"> {{_('Responded')}}</th>
                            <th width="5%"> {{_('Link')}}</th>
                            <th width="5%"> {{_('Edit')}}</th>
                            <th width="5%"> {{_('Delete')}}</th>

                        </tr>
                        </thead>
                        <tbody>
                        {% for guest in guests %}
                        <tr>
                            <td> {{ guest.name }}</td>
                            <td> {{ guest.email }}</td>
                            <td> {{ guest.number_of_guests }}</td>
                            <td>
                                <i class="fa {% if guest.last_viewed != None %} fa-check {% else %} fa-minus-square {% endif %}"></i>
                            </td>
                            <td>
                                <i class="fa {% if guest.last_responded != None %} fa-check {% else %} fa-minus-square {% endif %}"></i>
                            </td>
                            <td>
                                <a class="btn btn-link" href="{{ url_for('rsvp.rsvp_page', guest_id=guest.id) }}">
                                    <i class="fa fa-link"></i>
                                </a>
                            </td>
                            <td>
                                <a class="btn btn-link" href="{{ url_for('admin.edit_guest', guest_id=guest.id) }}">
                                    <i class="fa fa-pencil"></i>
                                </a>
                            </td>
                            <td>
                                <form action="{{ url_for('admin.delete_guest', guest_id=guest.id) }}" method="post">
                                    <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>
                                    <button type="submit" class="btn btn-link">
                                        <i class="fa fa-trash"></i>
                                    </button>
                                    </a>
                                </form>
                            </td>
                        </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
                <div style="text-align: center">

                    <a href="{{ url_for('admin.add_guest') }}" class="btn btn-default btn-lg">
                        <i class="fa fa-plus"></i>
                        {{_('Add')}}
                    </a>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

app/admin/templates/login.html
{% extends 'admin_base.html' %}

{% block navbar %}{% endblock %}

{% block app_content %}
<script>
    function onSubmitCallback(token) {}
</script>
<form action="" method="post" novalidate>
    {{ form.hidden_tag() }}
    <p>
        {{ form.password.label }}<br/>
        {{ form.password(size=32) }}<br/>
        {% if config.USE_RECAPTCHA_FOR_ADMIN %}{{ form.recaptcha }} {% endif %}
        <br/>
        {% for error in form.password.errors %}
        <span style="color: red;">[{{ error }}]</span>
        {% endfor %}
    </p>
    <p>{{ form.remember_me() }} {{ form.remember_me.label }}</p>
    <p>{{ form.submit() }}</p>
</form>

{% endblock %}

app/admin/templates/macros.html
{% macro generate_form(form) %}

<form action="" method="post">
{{ form.hidden_tag() }}
{% for field in form.data%}
    {% if field != 'csrf_token' %}
        {% set validity = ':valid' %}

        {% if form[field].type == 'BooleanField'%}
        <div class="form-row">
            <div class="col-sm-2"></div>
            <div class="col-sm-5">
                <div class="form-check">
                    {{ form[field](class_="form-check-input") }} {{ form[field].label(class_="form-check-label") }}<br/>
                </div>
            </div>
        </div>
        {% elif form[field].type == 'SubmitField' %}
        <div class="form-row">
            <div class="col-sm-5">{{ form.submit(class_="btn btn-primary") }}</div><br/>
        </div>
        {% else %}
        <div class="form-group row">
            {{ form[field].label(class="col-sm-2 col-form-label") }}
            <div class="col-sm-5">{{ form[field](class_="form-control", **kwargs) }}
            {% if form[field].errors %}
                {% for error in form[field].errors %}
            <div class="invalid-feedback">{{ error }}</div>
                {% endfor %}
            {% endif %}
            </div>
        </div>
        {% endif%}
  {% endif %}
{% endfor %}
</form>
{% endmacro %}